name = "j-madamis"
compatibility_date = "2024-08-18"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "madamis-db"
database_id = "7e359530-09dd-4617-a265-cccfeea5a5f0"
preview_database_id = "DB"
